### ISSUE TITLE
prefix for sio in example data is incorrect

### ISSUE THREAD

**Issue by markwilkinson** [CARE-SM/CARE-SM-Implementation#2]
sio prefix is:

http://semanticscience.org/resource/

**Comment by markwilkinson** [comment]
Original bug report (came in through FiaB)

yarrrml-rdfizer                  | arguments: /mnt/data/CARE_yarrrml.yaml --outputfile /mnt/data/triples/CARE.nq --serialization nquads
yarrrml-rdfizer                  | mapper arguments: --outputfile /mnt/data/triples/CARE.nq --serialization nquads
yarrrml-rdfizer                  | node:events:491
yarrrml-rdfizer                  |       throw er; // Unhandled 'error' event
yarrrml-rdfizer                  |       ^
yarrrml-rdfizer                  | 
yarrrml-rdfizer                  | Error: Invalid IRI found in prefix delcaration: "<https://sio.semanticscience.org/resource/"
yarrrml-rdfizer                  |     at Reader.error (/yarrrml-parser/node_modules/@graphy/content.ttl.read/main.js:873:9)

I'm not sure why getting the prefix wrong in the yarrrml would cause this error... but it may be related to having a different sio prefix in the CSV... (???)  Or something happens in the Hefesto stage?

It's a werid one!

**Comment by markwilkinson** [comment]
Oh... I see the problem.  You need to update the prefix, but that isn't what is causing the problem :-)

**Comment by pabloalarconm** [comment]
SIO prefix changed to http://semanticscience.org/resource/
