### ISSUE TITLE
Link to YARRRML template repository is faulty

### ISSUE THREAD

**Issue by wna-se** [CARE-SM/CARE-SM-Implementation#6]
The link to YARRRML template repository in README.md is leads to an internal page anchor without any reference to the mentioned repository. See bulled 3 under the section Standalone implementation.

Link to faulty link in code:
https://github.com/CARE-SM/CARE-SM-Implementation/blob/8bb00a14244775d3aed307acf43bfcc9b59c6c83/README.md?plain=1#L53

@pabloalarconm is this your repository?

**Comment by pabloalarconm** [comment]
Yes, looks like the link that sends you to the YARRRML templates are wrong. Thank you @wna-se, I will clarify the documentation.
